'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { parseFamilyCases, researchFamilies, type FamilyCase, type StatementAppearance } from '@/lib/research/families';
import { CasebookShell, ChapterHeading } from './CasebookShell';
import { EvidencePassage, SourceActions } from './EvidenceCollection';
function Appearance({ member }: { member: StatementAppearance }) {
  const date = member.source.publicationDate;
  return <article className="paper-sheet family-appearance"><p className="eyebrow">Retained page passage / publication {date.status === 'observed' || date.status === 'inferred' ? `${date.observation.value} (${date.status}, ${date.observation.precision} precision)` : date.status}</p><h3>{member.source.title ?? 'Untitled source'}</h3><EvidencePassage text={member.text} /><SourceActions url={member.source.sourceUrl} /><p className="fine-print">Retrieved: {member.source.provenance.retrievedAt ?? 'Unknown'}. Publication is not an event or capture date.</p><details className="research-method"><summary>{member.references.length} saved reference{member.references.length === 1 ? '' : 's'}</summary>{member.references.map((reference, index) => <p key={index}><Link className="text-link" href={`/casebook?case=${encodeURIComponent(reference.caseId)}&chapter=evidence`}>Inspect this saved investigation</Link><span className="fine-print"> · {reference.recordState === 'historical' ? 'Historical report; subsequent corrections need review' : reference.recordState === 'unassessed' ? 'Relationship unassessed' : 'Current saved report'} · source span {reference.start}–{reference.end} · publication {reference.publicationDate.status === 'observed' || reference.publicationDate.status === 'inferred' ? `${reference.publicationDate.observation.value} (${reference.publicationDate.status})` : reference.publicationDate.status} · retrieved {reference.retrievedAt ?? 'Unknown'}</span></p>)}</details></article>;
}
function Family({ family }: { family: ReturnType<typeof researchFamilies>['families'][number] }) {
  const [selected, setSelected] = useState(0), [shown, setShown] = useState(8);
  const edge = family.connections[selected], left = family.members.find(m => m.id === edge.from), right = family.members.find(m => m.id === edge.to);
  if (!left || !right) return null;
  return <section className="family-sheet"><div className="sheet-topline"><p className="eyebrow">{family.id.replace('-', ' ')} / connected retained statements</p><span className="state-label">{family.members.length} source passages</span></div><h2>Read the versions beside each other.</h2><div className="button-row family-pairs" aria-label="Choose a connected passage pair">{family.connections.slice(0, shown).map((connection, index) => <button className="paper-button" key={`${connection.from}:${connection.to}`} aria-pressed={selected === index} onClick={() => setSelected(index)}>Pair {index + 1} · {connection.status === 'same_retained_wording' ? 'Matching wording' : connection.status === 'same_source_variant' ? 'Same-page variant' : 'Plausible connection'}</button>)}{shown < family.connections.length ? <button className="paper-button" onClick={() => setShown(value => value + 8)}>More pairs</button> : null}</div><p className="family-relationship">{edge.status === 'same_retained_wording' ? 'Proven match of these retained words. Who copied whom, authorship and source independence remain unknown.' : edge.status === 'same_source_variant' ? 'Different retained wording from the same page across saved investigations. This may reflect a page edit or a different selected passage. Inspect the snapshots before calling it a correction.' : 'Substantial shared wording. Check changed figures, dates, places and scope. A shared claim or direction of spread is not established.'}</p><div className="family-pair-grid"><Appearance member={left} /><Appearance member={right} /></div><details className="research-method"><summary>Publication trail for this connected group</summary><p className="fine-print">Publication order in the retrieved sample. It does not establish social spread. Unknown dates are listed separately; year and month precision can overlap.</p><ol className="publication-trail">{[...family.members].sort((a, b) => { const date = (m: StatementAppearance) => m.source.publicationDate.status === 'observed' || m.source.publicationDate.status === 'inferred' ? m.source.publicationDate.observation.value : '9999'; return date(a).localeCompare(date(b)); }).map(member => <li key={member.id}><p>{member.source.publicationDate.status === 'observed' || member.source.publicationDate.status === 'inferred' ? `${member.source.publicationDate.observation.value} / ${member.source.publicationDate.status}` : `Date ${member.source.publicationDate.status}`} · {member.source.title ?? 'Untitled source'}</p><SourceActions url={member.source.sourceUrl} /></li>)}</ol></details></section>;
}
export default function ClaimFamilies() {
  const [cases, setCases] = useState<FamilyCase[] | null>(null), [error, setError] = useState(''), [omitted, setOmitted] = useState(0), [unreadable, setUnreadable] = useState(0);
  useEffect(() => {
    const controller = new AbortController();
    void (async () => {
      try {
        const response = await fetch('/api/research/families', { signal: controller.signal, cache: 'no-store' });
        const value: unknown = await response.json();
        if (!response.ok || !value || typeof value !== 'object' || !('cases' in value) || !('omittedCases' in value) || typeof value.omittedCases !== 'number' || !Number.isSafeInteger(value.omittedCases) || value.omittedCases < 0 || !('unreadableCases' in value) || typeof value.unreadableCases !== 'number' || !Number.isSafeInteger(value.unreadableCases) || value.unreadableCases < 0) throw new Error('The saved source sample could not be validated. Existing investigations are unchanged.');
        const parsed = parseFamilyCases(value.cases); if (controller.signal.aborted) return;
        setCases(parsed); setOmitted(value.omittedCases); setUnreadable(value.unreadableCases);
      } catch (error) { if (!controller.signal.aborted) setError(error instanceof Error ? error.message : 'Saved sources unavailable.'); }
    })();
    return () => controller.abort();
  }, []);
  const trail = useMemo(() => cases ? researchFamilies(cases) : null, [cases]);
  return <CasebookShell chapter="changes"><main id="main" tabIndex={-1} className="casebook-main"><ChapterHeading number="07" label="Related versions" description="ContextTrail connects inspected wording across your saved investigations automatically.">The words change.<br /><em>Keep their trail.</em></ChapterHeading><p className="family-intro">Find repeated wording and plausible variants. Compare the exact passages, their publication dates and the cases where they were retained. Repeated checks of the same page are merged, so they cannot manufacture new appearances.</p><div className="button-row"><Link className="paper-button primary" href="/questions">Investigate another question</Link><Link className="text-link" href="/watch">Follow new evidence</Link></div>{error ? <p role="alert" className="error-note">{error}</p> : !trail ? <p role="status">Connecting the retained source statements…</p> : <><p className="eyebrow">{trail.caseCount} saved investigations · {trail.sourceStatementCount} distinct retained statements · {trail.families.length} connected groups</p><p className="fine-print">This is a bounded comparison of the newest 20 saved investigations and at most 400 statements. {omitted + trail.omittedStatements + trail.omittedFamilies ? `Omitted from this view: ${omitted} cases, ${trail.omittedStatements} statements and ${trail.omittedFamilies} connected groups.` : ''} {unreadable ? `${unreadable} unreadable saved cases are preserved for recovery.` : ''} {trail.unconnectedCount} statements remain unconnected. Snippets are unresolved leads and do not enter these groups.</p>{trail.families.length ? <div className="family-stack">{trail.families.map(family => <Family family={family} key={family.id} />)}</div> : <p className="empty-state">No sufficiently close inspected passages were connected in this saved sample. This does not establish that a claim has no earlier version.</p>}</>}</main></CasebookShell>;
}
