'use client';
import { useState } from 'react';
import type { ExactAnchor } from '@/lib/inquiries/model';
import type { CaseEvidence } from '@/lib/cases/model';
import type { ResearchCaseView } from '@/lib/research/client';
import { EvidencePassage, SourceActions } from './EvidenceCollection';
import { currentMaterial } from './EvidenceDetail';
import {useChapterTour} from './ChapterTour';
export function EvidenceWorkbench({ view, onInspect, onFinding, onAdd }: { view: ResearchCaseView; onInspect: (evidence: CaseEvidence) => void; onFinding: (evidence: CaseEvidence, anchor?: ExactAnchor) => void; onAdd: () => void }) {
  const relevance = (evidence: CaseEvidence) => view.reportStatus === 'current' ? view.claimReport?.sources.find(source => source.evidenceId === evidence.id)?.relevance ?? -1 : -1;
  const evidence = [...view.caseRecord.evidence].sort((a,b) => relevance(b)-relevance(a));
  const [chosenKind, setKind] = useState<'passage' | 'region' | 'cell' | null>(null), [selected, setSelected] = useState(''), [page,setPage] = useState(0), [cell,setCell] = useState({row:0,column:0}), [region,setRegion] = useState<{x:number;y:number;width:number;height:number} | null>(null);
  useChapterTour(step=>{
    const available: Array<'passage'|'region'|'cell'>=[];
    if(evidence.some(item=>item.content.kind==='text'))available.push('passage');
    if(evidence.some(item=>currentMaterial(view,item.id)?.content.kind==='image'))available.push('region');
    if(evidence.some(item=>currentMaterial(view,item.id)?.content.kind==='table'))available.push('cell');
    setKind(available[Math.min(step,available.length-1)] ?? 'passage');setSelected('');setPage(0);setCell({row:0,column:0});setRegion(null);
  });
  const kind = chosenKind ?? (evidence.some(item => item.content.kind === 'text') ? 'passage' : evidence.some(item => currentMaterial(view,item.id)?.content.kind === 'image') ? 'region' : evidence.some(item => currentMaterial(view,item.id)?.content.kind === 'table') ? 'cell' : 'passage');
  const eligible = evidence.filter(item => kind === 'passage' ? item.content.kind === 'text' : currentMaterial(view,item.id)?.content.kind === (kind === 'region' ? 'image' : 'table'));
  const item = eligible.find(item => item.id === selected) ?? eligible[0], material = item ? currentMaterial(view,item.id) : null;
  return <section className="evidence-workbench" aria-label="Exact evidence workbench">
    <div className="evidence-kind-tabs" role="group" aria-label="Evidence anchor types">{([{id:'passage',letter:'P',title:'A passage',note:'Exact retained text'}, {id:'region',letter:'R',title:'An image region',note:'Alongside the full image'}, {id:'cell',letter:'T',title:'A table cell',note:'Row and column retained'}] as const).map(tab => <button key={tab.id} aria-pressed={kind === tab.id} onClick={() => { setKind(tab.id); setSelected(''); setPage(0); setCell({row:0,column:0}); setRegion(null); }}><span>{tab.letter}</span><div><h3>{tab.title}</h3><small>{tab.note}</small></div></button>)}</div>
    <article className="evidence-leaf">
      <div className="sheet-topline"><span className="eyebrow">{item ? item.content.kind === 'text' ? item.content.attribution.replaceAll('_',' ') : 'Retained source snapshot' : 'This selection stays open'}</span><span className="eyebrow">{kind === 'passage' ? 'Passage' : kind === 'region' ? 'Region' : 'Cell'}</span></div>
      {item ? <><h2>{item.title ?? 'Untitled source'}</h2><div className="evidence-leaf-content">{kind === 'passage' && item.content.kind === 'text' ? <EvidencePassage text={item.content.text} /> : material?.content.kind === 'image' ? <figure className="region-frame"><div className="region-preview"><img className="retained-image" src={`data:${material.content.mimeType};base64,${material.content.base64}`} alt="Complete retained image; click an area to select a region" onClick={event => {
          if (material.content.kind !== 'image') return;
          const bounds = event.currentTarget.getBoundingClientRect(), width = Math.max(1,Math.round(material.content.width/4)), height = Math.max(1,Math.round(material.content.height/4));
          const x = Math.max(0,Math.min(material.content.width-width,Math.round((event.clientX-bounds.left)/bounds.width*material.content.width-width/2)));
          const y = Math.max(0,Math.min(material.content.height-height,Math.round((event.clientY-bounds.top)/bounds.height*material.content.height-height/2)));
          setRegion({x,y,width,height});
        }} />{region ? <div className="selected-image-region" aria-label="Selected image region" style={{left:`${region.x/material.content.width*100}%`,top:`${region.y/material.content.height*100}%`,width:`${region.width/material.content.width*100}%`,height:`${region.height/material.content.height*100}%`}} /> : null}</div><figcaption>{region ? `Selected region: ${region.x}, ${region.y} · ${region.width} × ${region.height} pixels. Adjust the exact bounds in the finding editor.` : 'Click an area to select a region, or pin the complete image. Exact pixel bounds remain editable.'}</figcaption></figure> : material?.content.kind === 'table' ? <div className="material-scroll"><table className="material-table"><caption>Choose the cell you mean.</caption><thead><tr><th scope="col">Row</th>{material.content.columns.map((label,index) => <th scope="col" key={index}>{label || `Column ${index+1}`}</th>)}</tr></thead><tbody>{material.content.rows.map((row,index) => <tr key={index}><th scope="row">{index+1}</th>{row.map((value,column) => <td key={column}><button aria-pressed={cell.row === index && cell.column === column} onClick={() => setCell({row:index,column})}>{value || '(empty cell)'}</button></td>)}</tr>)}</tbody></table><p className="anchor-note">Row {cell.row+1} × {material.content.columns[cell.column] || `Column ${cell.column+1}`} · {material.content.rows[cell.row]?.[cell.column] || '(empty cell)'}</p></div> : null}</div>
      {relevance(item) >= 0 && relevance(item) < .5 ? <p className="fine-print">Low topic relevance. This retained passage is inspectable, not supporting evidence.</p> : null}
      <div className="evidence-leaf-footer"><p className="fine-print">Publication: {item.publicationDate.status === 'observed' || item.publicationDate.status === 'inferred' ? `${item.publicationDate.observation.value} (${item.publicationDate.status})` : item.publicationDate.status}. Retrieved: {item.provenance.retrievedAt ?? 'Unknown'}.</p><div className="button-row"><button className="paper-button primary" onClick={() => {
        const anchor: ExactAnchor | undefined = item.content.kind === 'text' ? {kind:'text',start:0,quote:item.content.text} : material?.content.kind === 'table' ? {kind:'table_cell',materialId:material.materialId,materialDigest:material.digest,row:cell.row,column:cell.column,value:material.content.rows[cell.row]?.[cell.column] ?? ''} : material?.content.kind === 'image' ? {kind:'image_region',materialId:material.materialId,materialDigest:material.digest,...(region ?? {x:0,y:0,width:material.content.width,height:material.content.height})} : undefined;
        onFinding(item, anchor);
      }}>Pin a finding to this evidence +</button><button className="text-link" aria-label="Inspect source details" onClick={() => onInspect(item)}>Inspect source details ↗</button></div><SourceActions url={item.sourceUrl} /></div></> : <><h2>{kind === 'passage' ? 'The trail starts with a source.' : kind === 'region' ? 'No retained image in this case.' : 'No retained table in this case.'}</h2><p>{kind === 'passage' ? 'Run an investigation to recover passages automatically, or add a source you already have.' : 'Original uploads are excluded from automatic saves. This view shows retained source material when it is present; it does not substitute illustrative evidence.'}</p><button className="text-link" onClick={onAdd}>Add evidence</button></>}
    </article>
    {eligible.length ? <div className="evidence-source-tabs" role="group" aria-label="Retained evidence selection">{eligible.slice(page*8,page*8+8).map((source,index) => <button key={source.id} aria-pressed={source.id === item?.id} onClick={() => { setSelected(source.id); setCell({row:0,column:0}); setRegion(null); }}><span className="eyebrow">{String(page*8+index+1).padStart(2,'0')}</span>{source.title ?? new URL(source.sourceUrl).hostname}</button>)}<div className="button-row"><button className="text-link" disabled={!page} onClick={() => setPage(value => value-1)}>← Previous sources</button><button className="text-link" disabled={(page+1)*8>=eligible.length} onClick={() => setPage(value => value+1)}>Next sources →</button><button className="text-link" onClick={onAdd}>Add evidence</button></div></div> : null}
  </section>;
}
