"""Reproducible, local ContextTrail launch film. No network or fabricated UI."""
from pathlib import Path
import json, math, html, shutil
import numpy as np
import soundfile as sf

P = Path(__file__).resolve().parent
A = P / 'assets/launch-20261005'
C = P / 'compositions/launch-20261005'
C.mkdir(exist_ok=True)
if not (P/'index-before-launch-20261005.html.txt').exists():
    shutil.copy2(P/'index.html', P/'index-before-launch-20261005.html.txt')
shutil.copy2(P/'node_modules/gsap/dist/gsap.min.js', A/'gsap.min.js')
shutil.copy2(P.parent.parent/'public/illustrative-earthrise.jpg', A/'earthrise.jpg')

meta=json.loads((P/'audio_meta_launch_20261005.json').read_text())
request=json.loads((P/'audio_request_launch_20261005.json').read_text())
sr=48000; beat=.625
holds=[1.6,1.6,1.5,2.5,2.3,1.8,2,3.2,3.3]
scenes=[]; cursor=0; caps=[]
for i,v in enumerate(meta['voices']):
    pcm, native=sf.read(P/v['path'])
    if pcm.ndim>1: pcm=pcm.mean(axis=1)
    duration=len(pcm)/native
    pcm=np.interp(np.arange(round(duration*sr))/sr,np.arange(len(pcm))/native,pcm)
    length=math.ceil((duration+.35+holds[i])/beat)*beat
    scenes.append(dict(n=i+1,start=round(cursor,3),duration=length,voice_start=round(cursor+.35,3),voice_duration=duration,text=request['lines'][i]['text']))
    # The aligner's end occasionally exceeds the PCM. Clamp a proportional
    # correction instead of letting subtitles run into the next scene.
    words=[]
    for word in v['words']:
        if words and words[-1]['text'].lower()=='context' and word['text'].lower().startswith('trail'):
            words[-1]['text']='ContextTrail.';words[-1]['end']=word['end']
        else:words.append(dict(word))
    factor=min(1,duration/max(w['end'] for w in words))
    for j in range(0,len(words),6):
        group=words[j:j+6]
        text=' '.join(w['text'] for w in group).replace('Context Trail,','ContextTrail.').replace('the Passage.','the passage.')
        st=cursor+.35+group[0]['start']*factor
        end=min(cursor+.35+duration,cursor+.35+group[-1]['end']*factor+.06)
        caps.append(dict(start=round(st,3),end=round(end,3),text=text))
    cursor+=length
for i,c in enumerate(caps[:-1]):
    c['end']=min(c['end'],caps[i+1]['start']-.025)
total=cursor
voice=np.zeros(round(total*sr))
for sc,v in zip(scenes,meta['voices']):
    pcm, native=sf.read(P/v['path']); pcm=pcm.mean(axis=1) if pcm.ndim>1 else pcm
    pcm=np.interp(np.arange(round(len(pcm)/native*sr))/sr,np.arange(len(pcm))/native,pcm)
    offset=round(sc['voice_start']*sr);voice[offset:offset+len(pcm)]=pcm
voice=voice/max(.001,np.max(np.abs(voice)))*.82
sf.write(A/'narration.wav',voice,sr,subtype='PCM_24')

# Original score: a restrained 96 BPM plucked motif, changing bass harmony,
# soft brush percussion, and a resolving final chord. Every note is specified.
music=np.zeros((round(total*sr),2))
def note(start,midi,duration,gain,pan=0):
    count=round(duration*sr); t=np.arange(count)/sr; freq=440*2**((midi-69)/12)
    env=(1-np.exp(-t*90))*np.exp(-t*2.4)
    wave=(np.sin(2*np.pi*freq*t)+.24*np.sin(2*np.pi*freq*2*t)+.07*np.sin(2*np.pi*freq*3*t))*env*gain
    off=round(start*sr); count=min(count,len(music)-off)
    if count>0: music[off:off+count]+=wave[:count,None]*np.array([math.sqrt((1-pan)/2),math.sqrt((1+pan)/2)])
chords=[[50,57,62,65],[53,60,65,69],[48,55,60,64],[46,53,58,62]]
for b in range(math.ceil(total/beat)):
    when=b*beat; bar=b//4; chord=chords[(bar//2)%4]
    if b%4==0:
        note(when,chord[0]-12,2.4,.035)
    if b%2==0:
        motif=[0,2,1,3,2,1,3,2]; midi=chord[motif[(b//2)%8]]+12
        note(when,midi,1.7,.024,(-.3 if b%4==0 else .3))
    if b%4==2:
        note(when,chord[1],1.4,.011)
    # Quiet synthesized brush, not an imitation of interface action sounds.
    if b%2==1:
        t=np.arange(round(.09*sr))/sr
        brush=(np.sin(2*np.pi*4401*t)+np.sin(2*np.pi*6089*t))*np.exp(-t*58)*.002
        off=round(when*sr);n=min(len(brush),len(music)-off)
        music[off:off+n]+=brush[:n,None]
for k,m in enumerate([50,57,62,65,69]): note(total-4+k*.055,m,3.8,.026,k*.12-.24)
envelope=np.ones(len(music)); fadein=np.minimum(np.arange(len(music))/sr/1.1,1); fadeout=np.clip((total-np.arange(len(music))/sr)/2.2,0,1)
music*= (fadein*fadeout)[:,None]*7
sf.write(A/'original-score.wav',music,sr,subtype='PCM_24')

BASE='''@font-face{font-family:Instrument;src:url(assets/fonts/InstrumentSerif-Regular.woff2)}@font-face{font-family:Instrument;src:url(assets/fonts/InstrumentSerif-Regular-Italic.woff2);font-style:italic}@font-face{font-family:Geist;src:url(assets/fonts/GeistSans-Regular.woff2)}*{box-sizing:border-box;margin:0} .bg{position:absolute;inset:0;background:var(--paper)} .eyebrow{font:24px/1.4 Geist,Arial,sans-serif;letter-spacing:3px;text-transform:uppercase} .title{font:112px/1.02 Instrument,Georgia,serif;letter-spacing:-1px} .small{font:29px/1.4 Geist,Arial,sans-serif} .serif{font-family:Instrument,Georgia,serif} .window{position:absolute;left:240px;top:125px;width:1440px;height:810px;overflow:hidden;box-shadow:14px 18px 0 rgba(34,44,41,.13);border:1px solid #a99b80;background:#222c29} .camera{position:absolute;left:0;top:0;width:1280px;height:720px;transform-origin:0 0} .camera img{display:block;width:1280px;height:720px} .shot{position:absolute;inset:0} .record{position:absolute;left:240px;top:70px;font:22px Geist,Arial,sans-serif;letter-spacing:.3px} .sheet{background:var(--sheet);border:1px solid #a99b80;box-shadow:12px 14px 0 rgba(34,44,41,.15)} .ink{background:var(--ink);color:var(--paper)} .rule{border-top:1px solid currentColor;opacity:.4} .note{position:absolute;background:var(--blue);color:var(--paper);padding:18px 28px;font:40px/1.1 Instrument,Georgia,serif;box-shadow:6px 7px 0 #e2bd58} .trail{position:absolute;fill:none;stroke:var(--rust);stroke-width:3} .tag{font:23px/1.5 Geist,Arial,sans-serif;letter-spacing:1px;text-transform:uppercase} .dot{width:14px;height:14px;background:var(--rust);border-radius:50%;position:absolute}'''
mark='''<svg viewBox="0 0 40 30" fill="none" aria-label="ContextTrail mark"><path d="M2 7h25v19H2zM11 2h26v18H27M16 11l10 6-10 6M7 17h18" stroke="currentColor" stroke-width="1.4"/></svg>'''
def shot(id,asset):
    return f'<div id="{id}" class="shot"><div id="{id}-camera" class="camera" data-layout-allow-overflow="true"><img src="assets/launch-20261005/{asset}.png" alt="Actual ContextTrail production UI: {asset}" data-layout-allow-overflow="true"></div></div>'
def scene(n,markup,css,js):
    cid=f'launch-{n:02d}'; root=f'{cid}-root'
    content=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"></head><body><template><style>#{root}{{position:absolute;inset:0;width:100%;height:100%;overflow:hidden;color:var(--ink);font-family:Geist,Arial,sans-serif}} {BASE} {css}</style><section id="{root}" data-composition-id="{cid}" data-width="1920" data-height="1080"><div class="bg"></div>{markup}</section><script>(()=>{{const tl=gsap.timeline({{paused:true}});{js}window.__timelines['{cid}']=tl;}})();</script></template></body></html>'''
    (C/f'{cid}.html').write_text(content)

scene(1,f'''<div id="opening-ink"></div><p class="eyebrow" id="opening-label">The story travels. The context disappears.</p><h1 id="opening-title" class="title">Same image.<br><em>Different story.</em></h1><div class="sheet" id="fragment-image" data-layout-allow-overflow="true"><img src="assets/launch-20261005/earthrise.jpg" alt="Earthrise photograph used as an opening visual"><p>Reposted.</p></div><div class="sheet" id="fragment-date"><p class="eyebrow">The date</p><div class="title">Today?</div><span class="small">A clip loses its context.</span></div><div class="sheet" id="fragment-answer"><p class="eyebrow">The answer</p><p class="serif">It sounds certain.</p><span class="small">Where is the source?</span></div><div id="question-sheet" data-layout-allow-overflow="true" class="sheet"><span class="eyebrow">One question</span><h2 class="title">Where did it<br><em>come from?</em></h2></div>''', '''#opening-ink{position:absolute;inset:0;background:var(--ink)}#opening-label{position:absolute;left:140px;top:75px;color:var(--paper)}#opening-title{position:absolute;left:140px;top:145px;color:var(--paper);font-size:124px}#opening-title em{color:#e2bd58}#fragment-image{position:absolute;left:140px;top:465px;width:470px;padding:22px;transform:rotate(-4deg)}#fragment-image img{width:424px;height:270px;object-fit:cover}#fragment-image p{font:40px Instrument;margin-top:10px}#fragment-date{position:absolute;left:660px;top:500px;width:485px;padding:38px;height:340px;transform:rotate(3deg)}#fragment-date .title{margin:30px 0;font-size:100px;color:var(--rust)}#fragment-answer{position:absolute;left:1200px;top:450px;width:520px;height:340px;padding:38px;transform:rotate(-2deg)}#fragment-answer .serif{font-size:72px;margin:28px 0}#question-sheet{position:absolute;left:505px;top:230px;width:910px;height:615px;padding:62px}#question-sheet h2{font-size:134px;margin-top:46px}#question-sheet em{color:var(--rust)}''', '''tl.fromTo('#opening-title',{y:28,opacity:0},{y:0,opacity:1,duration:.55,ease:'power3.out'},.05);tl.fromTo('#fragment-image',{y:100,rotation:-9},{y:0,rotation:-4,duration:.7,ease:'power4.out'},.4);tl.fromTo('#fragment-date',{y:90,rotation:8,opacity:0},{y:0,rotation:3,opacity:1,duration:.6,ease:'power3.out'},1.9);tl.fromTo('#fragment-answer',{x:400,opacity:0},{x:0,opacity:1,duration:.65,ease:'power3.out'},3.4);tl.fromTo('#question-sheet',{x:1650,rotation:-5},{x:0,rotation:0,duration:.7,ease:'power4.inOut'},5.8);tl.to(['#fragment-image','#fragment-date','#fragment-answer'],{y:30,opacity:0,duration:.3,ease:'power2.in'},5.6);tl.to('#opening-title',{opacity:0,duration:.25},5.55);''')
scene(2,f'''<div id="intro-rule"></div><div id="intro-text"><p class="eyebrow">Built by Vasu</p><h1 class="title">Hi, I’m <em>Vasu.</em></h1><div id="intro-brand">{mark}<span>ContextTrail</span></div><p class="serif" id="intro-purpose">A place to follow the question.<br>And keep the evidence.</p></div><div class="window" id="intro-cover">{shot('intro-cover-shot','cover')}</div>''','''#intro-rule{position:absolute;left:130px;right:130px;top:85px;border-top:1px solid #a99b80}#intro-text{position:absolute;left:140px;top:210px}#intro-text h1{font-size:152px;margin-top:34px}#intro-text em{color:var(--rust)}#intro-brand{display:flex;gap:24px;align-items:center;margin-top:50px;font:78px Instrument}#intro-brand svg{width:100px;height:78px}#intro-purpose{font-size:52px;line-height:1.13;margin-top:42px}#intro-cover{left:240px;top:125px;width:1440px;height:810px;transform-origin:0 0}''', '''tl.fromTo('#intro-text',{x:-45,opacity:0},{x:0,opacity:1,duration:.6,ease:'power3.out'},.1);tl.fromTo('#intro-brand',{y:40,opacity:0},{y:0,opacity:1,duration:.6,ease:'power3.out'},1.65);tl.fromTo('#intro-cover',{x:1050,y:95,scale:.528,rotation:4,opacity:0},{x:770,y:95,scale:.528,rotation:-1,opacity:1,duration:.8,ease:'power4.out'},2.4);gsap.set('#intro-cover-shot-camera',{scale:1.125,x:0,y:0});tl.fromTo('#intro-purpose',{y:20,opacity:0},{y:0,opacity:1,duration:.5,ease:'power2.out'},3.2);tl.to('#intro-text',{opacity:0,duration:.3},5.5);tl.to('#intro-cover',{x:0,y:0,scale:1,rotation:0,duration:.8,ease:'power4.inOut'},5.6);''')
scene(3,'''<p class="record">01 / Image · real retained investigation</p><div class="window" id="image-window">'''+shot('image-input-shot','image-input')+shot('image-sources-shot','image-sources')+'''</div><div id="origin-note" class="note">13 pages. Reporting origins still unresolved.</div>''','''#origin-note{left:280px;top:835px}''','''gsap.set('#image-input-shot-camera',{scale:1.125});gsap.set('#image-sources-shot-camera',{scale:1.125});gsap.set('#image-sources-shot',{opacity:0});tl.fromTo('#image-window',{y:130,rotation:2},{y:0,rotation:0,duration:.8,ease:'power4.out'},0);tl.to('#image-input-shot-camera',{scale:1.45,x:-390,y:-110,duration:.75,ease:'power3.inOut'},1.1);tl.to('#image-sources-shot',{opacity:1,duration:.12},3.8);tl.to('#image-sources-shot-camera',{scale:1.36,x:-50,y:-30,duration:.8,ease:'power3.inOut'},5.9);tl.fromTo('#origin-note',{x:-70,opacity:0},{x:0,opacity:1,duration:.45,ease:'power3.out'},6.7);''')
scene(4,'''<p class="record">04 / Evidence · NASA Science · retained passage</p><div class="window" id="evidence-window">'''+shot('nasa-evidence-shot','image-evidence-nasa')+shot('nasa-inspector-shot','nasa-inspector')+'''</div><div id="date-note" class="note">A page date ≠ the photograph’s date.</div>''','''#date-note{left:450px;top:832px}''','''gsap.set('#nasa-evidence-shot-camera',{scale:1.125});gsap.set('#nasa-inspector-shot-camera',{scale:1.125});gsap.set('#nasa-inspector-shot',{opacity:0});tl.fromTo('#evidence-window',{x:110},{x:0,duration:.6,ease:'power3.out'},0);tl.to('#nasa-inspector-shot',{opacity:1,duration:.12},1.2);tl.to('#nasa-inspector-shot-camera',{scale:1.65,x:-340,y:-160,duration:.9,ease:'power3.inOut'},1.6);tl.to('#nasa-inspector-shot-camera',{scale:1.75,x:-700,y:-180,duration:.9,ease:'power3.inOut'},5.55);tl.fromTo('#date-note',{y:50,rotation:-2,opacity:0},{y:0,rotation:0,opacity:1,duration:.5,ease:'power3.out'},7.0);''')
scene(5,'''<p class="record">03 / Questions → 08 / AI answers · same image case</p><div class="window" id="finding-window">'''+shot('pin-shot','pin-finding-form')+shot('finding-shot','image-finding')+shot('answer-shot','image-ai-answers')+'''</div><div id="binding-note" class="note">Exact words. A visible source span.</div>''','''#binding-note{left:280px;top:837px}''','''gsap.set('#pin-shot-camera',{scale:1.125});gsap.set('#finding-shot-camera',{scale:1.7,x:-480,y:-400});gsap.set('#answer-shot-camera',{scale:1.35,x:-90,y:-40});gsap.set(['#finding-shot','#answer-shot'],{opacity:0});tl.fromTo('#finding-window',{x:120},{x:0,duration:.55,ease:'power3.out'},0);tl.to('#finding-shot',{opacity:1,duration:.1},1.6);tl.to('#answer-shot',{opacity:1,duration:.12},3.75);tl.to('#answer-shot-camera',{scale:1.7,x:-620,y:-230,duration:.8,ease:'power3.inOut'},4.25);tl.fromTo('#binding-note',{x:-60,opacity:0},{x:0,opacity:1,duration:.5,ease:'power3.out'},5.3);''')
scene(6,'''<p class="eyebrow" id="question-label">A separate question investigation</p><h1 class="title" id="question-title">Room for another<br><em>explanation.</em></h1><div class="window" id="question-window">'''+shot('question-shot','question-real')+'''</div><div id="question-counts"><div><strong>12</strong><span>Sources retained</span></div><div><strong>3</strong><span>Quotes inspected</span></div><div><strong>9</strong><span>Leads still open</span></div></div>''','''#question-label{position:absolute;left:130px;top:80px}#question-title{position:absolute;left:130px;top:190px;font-size:96px;width:620px}#question-title em{color:var(--rust)}#question-window{left:780px;top:160px;width:1010px;height:650px}#question-counts{position:absolute;left:130px;top:650px;display:flex;gap:40px}#question-counts div{width:175px;border-top:1px solid #a99b80;padding-top:25px}#question-counts strong{font:110px Instrument;color:var(--rust);display:block}#question-counts span{font:23px/1.4 Geist;display:block;margin-top:15px}''','''gsap.set('#question-shot-camera',{scale:1.4,x:-660,y:-230});tl.fromTo('#question-window',{x:150,rotation:2},{x:0,rotation:0,duration:.8,ease:'power4.out'},.1);tl.fromTo('#question-title',{y:30,opacity:0},{y:0,opacity:1,duration:.55,ease:'power3.out'},.2);tl.fromTo('#question-counts div',{y:35,opacity:0},{y:0,opacity:1,duration:.45,stagger:.22,ease:'power3.out'},2.6);''')
scene(7,'''<div id="video-ground"></div><p class="eyebrow" id="video-label">02 / Video · a separate retained investigation</p><div id="supplied-video"><video id="demo-video" class="clip" src="assets/delhi-caption-input.mp4" muted playsinline data-start="0" data-duration="'''+str(scenes[6]['duration'])+'''" data-media-start="10.5" data-track-index="1"></video></div><p id="clip-label" class="small">Supplied clip · original recording</p><div id="video-ui-window" class="window">'''+shot('video-ui-shot','video-moment-10-5')+'''</div><p id="video-status" class="note">Identity remains unconfirmed.</p><p id="video-time" class="serif">Searched offset · 00:10.500</p>''','''#video-ground{position:absolute;inset:0;background:var(--ink)}#video-label{position:absolute;left:130px;top:80px;color:var(--paper)}#supplied-video{position:absolute;left:130px;top:190px;width:660px;height:620px;overflow:hidden;border:1px solid #748279}#demo-video{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}#clip-label{position:absolute;left:130px;top:825px;color:var(--paper)}#video-ui-window{left:835px;top:190px;width:955px;height:620px;border-color:#748279}#video-status{left:885px;top:730px}#video-time{position:absolute;left:130px;top:895px;font-size:42px;color:#e2bd58}''','''gsap.set('#video-ui-shot-camera',{scale:1.45,x:-830,y:-85});tl.fromTo('#supplied-video',{x:-100,opacity:0},{x:0,opacity:1,duration:.65,ease:'power3.out'},.1);tl.fromTo('#video-ui-window',{x:150,opacity:0},{x:0,opacity:1,duration:.65,ease:'power3.out'},.7);tl.fromTo('#video-status',{y:45,opacity:0},{y:0,opacity:1,duration:.45,ease:'power3.out'},3.7);tl.to('#video-ui-shot-camera',{scale:1.3,x:-160,y:-270,duration:.8,ease:'power3.inOut'},5.8);''')
scene(8,'''<p class="record">Saved cases · Changes · Watch</p><div class="window" id="return-window">'''+shot('saved-shot','saved-casebook')+shot('changes-shot','image-changes')+shot('watch-shot','watch-paused-inspector')+'''</div><div class="note" id="return-note">Keep the trail. Come back.</div>''','''#return-note{left:280px;top:840px}''','''gsap.set('#saved-shot-camera',{scale:1.5,x:-140,y:-60});gsap.set('#changes-shot-camera',{scale:1.125});gsap.set('#watch-shot-camera',{scale:1.5,x:-240,y:-195});gsap.set(['#changes-shot','#watch-shot'],{opacity:0});tl.fromTo('#return-window',{y:90},{y:0,duration:.6,ease:'power3.out'},0);tl.to('#changes-shot',{opacity:1,duration:.1},2.2);tl.to('#watch-shot',{opacity:1,duration:.12},4.1);tl.fromTo('#return-note',{y:40,opacity:0},{y:0,opacity:1,duration:.5,ease:'power3.out'},6.2);''')
scene(9,f'''<div id="end-papers"><div class="sheet" id="end-sheet-1"></div><div class="sheet" id="end-sheet-2"></div><div class="sheet" id="end-sheet-3"></div></div><div id="end-mark">{mark}</div><p class="eyebrow" id="end-label">The question doesn’t end when the tab closes.</p><h1 class="title" id="end-title">Follow the<br><em>question.</em></h1><div id="end-brand">ContextTrail</div><div class="ink" id="end-cta">Bring your question ↗</div>''','''#end-papers{position:absolute;left:1240px;top:320px;width:420px;height:440px}#end-papers .sheet{position:absolute;inset:0}#end-sheet-1{transform:rotate(-9deg)}#end-sheet-2{transform:rotate(6deg)}#end-mark{position:absolute;left:1310px;top:415px;width:300px;color:var(--rust)}#end-mark svg{width:100%;height:230px}#end-label{position:absolute;left:140px;top:100px}#end-title{position:absolute;left:140px;top:220px;font-size:180px}#end-title em{color:var(--rust)}#end-brand{position:absolute;left:140px;top:670px;font:84px Instrument}#end-cta{position:absolute;left:140px;top:795px;padding:27px 40px;font:31px Geist;border-bottom:5px solid #e2bd58}''','''tl.fromTo('#end-papers .sheet',{x:500,rotation:30},{x:0,rotation:(i)=>[-9,6,0][i],duration:.75,stagger:.12,ease:'power4.out'},.1);tl.fromTo('#end-title',{y:35,opacity:0},{y:0,opacity:1,duration:.7,ease:'power3.out'},.25);tl.fromTo('#end-mark',{scale:.65,opacity:0},{scale:1,opacity:1,duration:.7,ease:'back.out(1.2)'},1.2);tl.fromTo('#end-brand',{y:20,opacity:0},{y:0,opacity:1,duration:.45},3.0);tl.fromTo('#end-cta',{x:-35,opacity:0},{x:0,opacity:1,duration:.45,ease:'power3.out'},4.0);''')

# Actual timestamps; captions are a separate scene track with seek-safe clips.
caption_markup=''.join(f'<div id="launch-caption-{i}" class="clip" data-start="{c["start"]}" data-duration="{c["end"]-c["start"]:.3f}" data-track-index="{i//4}"><p class="caption-text">{html.escape(c["text"])}</p></div>' for i,c in enumerate(caps))
(C/'captions.html').write_text(f'''<!doctype html><html><body><template><style>#launch-captions-root{{position:absolute;inset:0;pointer-events:none}}.caption-text{{position:absolute;bottom:27px;left:50%;transform:translateX(-50%);max-width:1600px;white-space:nowrap;padding:12px 25px;background:#222c29;color:#f2eddc;font:32px/1.35 Geist,Arial,sans-serif;border-bottom:2px solid #e2bd58}}</style><div id="launch-captions-root" data-composition-id="launch-captions" data-width="1920" data-height="1080">{caption_markup}</div><script>window.__timelines['launch-captions']=gsap.timeline({{paused:true}});</script></template></body></html>''')
hosts=''.join(f'<div id="launch-host-{s["n"]}" class="clip" data-composition-id="launch-{s["n"]:02d}" data-composition-src="compositions/launch-20261005/launch-{s["n"]:02d}.html" data-start="{s["start"]}" data-duration="{s["duration"]}" data-track-index="{(s["n"]-1)%3}" data-width="1920" data-height="1080"></div>' for s in scenes)
(P/'index.html').write_text(f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><title>ContextTrail — Follow the question</title><script src="assets/launch-20261005/gsap.min.js"></script><style>@font-face{{font-family:Instrument;src:url(assets/fonts/InstrumentSerif-Regular.woff2)}}@font-face{{font-family:Instrument;src:url(assets/fonts/InstrumentSerif-Regular-Italic.woff2);font-style:italic}}@font-face{{font-family:Geist;src:url(assets/fonts/GeistSans-Regular.woff2)}}:root{{--paper:#f2eddc;--sheet:#faf6e8;--ink:#222c29;--rust:#a93f2e;--blue:#234d70}}*{{box-sizing:border-box}}html,body{{margin:0;width:1920px;height:1080px;overflow:hidden;background:var(--paper)}}#launch{{position:relative;width:100%;height:100%}}.clip{{position:absolute;inset:0;overflow:hidden}}</style></head><body><main id="launch" data-composition-id="launch" data-width="1920" data-height="1080" data-duration="{total}">{hosts}<div id="launch-captions-host" class="clip" data-composition-id="launch-captions" data-composition-src="compositions/launch-20261005/captions.html" data-start="0" data-duration="{total}" data-track-index="4" data-width="1920" data-height="1080"></div><audio id="narration" class="clip" src="assets/launch-20261005/narration.wav" data-start="0" data-duration="{total}" data-track-index="5" data-volume="1"></audio><audio id="music-bed" class="clip" src="assets/launch-20261005/original-score.wav" data-start="0" data-duration="{total}" data-track-index="6" data-volume="1"></audio></main><script>window.__timelines=window.__timelines||{{}};window.__timelines['launch']=gsap.timeline({{paused:true}});</script></body></html>''')
(P/'launch-timing.json').write_text(json.dumps(dict(duration=total,fps=60,beat_seconds=beat,scenes=scenes,captions=caps),indent=2))
def stamp(s):
    ms=round(s*1000);h,ms=divmod(ms,3600000);m,ms=divmod(ms,60000);sec,ms=divmod(ms,1000);return f'{h:02}:{m:02}:{sec:02}.{ms:03}'
(P/'captions-launch.vtt').write_text('WEBVTT\n\n'+'\n\n'.join(f'{stamp(c["start"])} --> {stamp(c["end"])}\n{c["text"]}' for c in caps)+'\n')
(P/'captions-launch.srt').write_text('\n\n'.join(f'{i+1}\n{stamp(c["start"]).replace(".",",")} --> {stamp(c["end"]).replace(".",",")}\n{c["text"]}' for i,c in enumerate(caps))+'\n')
for name,body in {
 'BRIEF.md':f'''\n\n## 2026-10-05 — full launch film\nProblem first, exact Vasu introduction second, then real production app demonstrations. {total:.3f} seconds, 1920×1080, 60 fps. Original editorial motion using the product's serif, paper, rust, blue, and mark. Studied Jev, Berlified, Pocketsflow, Leon Lin and Space; links and observations in REFERENCES-20261005.md. UI captured through actual computer-use interaction. The image run, question run, video run and watch are distinct retained real investigations. No invented corrections or confirmed identities. Local Kokoro am_michael narration is generated, not Vasu's recorded voice. Original locally synthesized 96 BPM score. No external upload or publication. Existing earlier film archived at index-before-launch-20261005.html.txt. No subagents.\n''',
 'STORYBOARD.md':'\n\n## 2026-10-05 — problem → builder → evidence → return\n'+ '\n'.join(f'{s["start"]:.3f}–{s["start"]+s["duration"]:.3f} | {s["n"]:02d} | {s["text"]}' for s in scenes)+'\n\nVisual beats: lost-context fragments gather into a question sheet; Vasu and real cover; image input to unresolved source map; NASA quote then publication-date inspector; saved finding to selected answer span; separate question and honest coverage counts; original supplied video beside retained leads; saved cases, starting snapshot and paused watch; paper sheets resolve into the ContextTrail mark. UI pixels remain unchanged. Camera reframes and explicit holds direct attention.\n',
 'frame.md':f'\n\n## 2026-10-05 launch cut\n{total:.3f}s landscape editorial film; Instrument Serif + Geist Sans. Paper #f2eddc, sheet #faf6e8, ink #222c29, rust #a93f2e, blue #234d70, gold #e2bd58. Local fonts/scripts, readable quote holds, 96 BPM beat grid, generated narration. Nine independently registered sub-compositions plus caption track.\n'
}.items():
    p=P/name
    if '## 2026-10-05 — full launch film' not in p.read_text() if name=='BRIEF.md' else '## 2026-10-05' not in p.read_text():
        with p.open('a') as f:f.write(body)
provenance={
 'ui':{'method':'Actual production app interactions through computer use; successive states captured unchanged. Editorial camera framing is applied outside the app.','origin':'http://127.0.0.1:3241','image_case':'5d1b0875-3884-42d0-a5a9-5278dfa06dc7','question_case':'research-afec2a13-1ba9-44fc-9b70-ceef89fa46ad','video_case':'research-55069ef5-81db-4f94-95fb-9c129582f445','watch':'Paused UPI watch; no new check or resume performed.','finding':'Local source-bound finding saved during actual demo. Reviewer label ContextTrail launch demo.'},
 'video':{'path':'assets/delhi-caption-input.mp4','ownership':'Existing user project supplied recording','offset':10.5,'display':'Original recording alongside retained source UI. Not reconstructed as persisted app frames.'},
 'voice':{'provider':'local Kokoro','voice':'am_michael','identity':'Generated narration; not a recording or clone of Vasu.'},
 'music':{'path':'assets/launch-20261005/original-score.wav','rights':'Original synthesized composition authored locally by build-launch-20261005.py','bpm':96},
 'references':'REFERENCES-20261005.md','ui_assets':sorted(str(p.relative_to(P)) for p in A.glob('*.png'))}
(P/'launch-media.json').write_text(json.dumps(provenance,indent=2))
print(json.dumps(dict(duration=total,scene_count=len(scenes),caption_count=len(caps),voice_seconds=float(np.count_nonzero(voice)/sr))))
