/** Independently generated solid/checkered pixels and invented table values; no external assets. */
import { createHash } from 'node:crypto';
import { writeFile } from 'node:fs/promises';
import { PNG } from 'pngjs';
function image(changed) {
  const png = new PNG({ width: 8, height: 6 });
  for (let y = 0; y < png.height; y++) for (let x = 0; x < png.width; x++) {
    const i = (y * png.width + x) * 4;
    png.data.set([x * 20, y * 30, changed ? 240 : 40, 255], i);
  }
  const bytes = PNG.sync.write(png, { colorType: 6, inputColorType: 6 });
  return { base64: bytes.toString('base64'), width: png.width, height: png.height, contentHash: `sha256:${createHash('sha256').update(bytes).digest('hex')}` };
}
const fixture = { rights: 'Synthetic pixels and invented values generated by this script for project verification.', image: image(false), replacement: image(true), table: { kind: 'table', columns: ['Period', 'Reported count'], rows: [['2025', '12'], ['2026', '18'], ['', '=1+1']] } };
await writeFile(new URL('./synthetic.json', import.meta.url), `${JSON.stringify(fixture, null, 2)}\n`);
